# WebAgent UAT Environment Configuration

# API settings
api:
  version: "v1"
  prefix: "/api/v1"
  debug_mode: false
  host: "0.0.0.0"
  port: 8000

# CORS settings
cors:
  origins:
    - "https://uat.webagent.example.com"
    - "https://uat-admin.webagent.example.com"
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

# Database settings
database:
  vector_db:
    path: "/data/vectordb"
    embedding_dimension: 1536
    distance_metric: "cosine"
  redis:
    host: "redis"
    port: 6379
    db: 0
    password: null
    key_prefix: "webagent:uat:"

# LLM settings
llm:
  provider: "together"
  default_model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
  temperature: 0.5
  timeout_seconds: 90
  max_tokens: 8192
  retry_attempts: 3
  batch_size: 20

# LangSmith settings for observability
langsmith:
  project_name: "webagent-research-uat"
  tracing_enabled: true
  log_level: "INFO"

# Web search settings
web_search:
  provider: "tavily"
  search_depth: "comprehensive"
  max_results: 15
  include_domains: []
  exclude_domains: []
  timeout_seconds: 60

# Task management
tasks:
  max_concurrent: 20
  result_ttl_minutes: 120
  history_ttl_days: 14
  max_retries: 3

# Agents configuration
agents:
  supervisor:
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    temperature: 0.2
  web_research:
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    temperature: 0.3
    max_searches_per_task: 5
  internal_research:
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    temperature: 0.1
    max_documents: 20
  senior_research:
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    temperature: 0.2
    max_follow_up_questions: 3
  data_analysis:
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    temperature: 0.1
  coding:
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    temperature: 0.0
    allowed_modules: ["matplotlib", "seaborn", "numpy", "pandas"]
    timeout_seconds: 30
  team_manager:
    model: "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free"
    temperature: 0.4

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  log_to_file: true
  log_file: "/var/log/webagent/webagent-uat.log"
  rotate_logs: true
  max_file_size_mb: 20
  backup_count: 10

# Security settings
security:
  token_expire_minutes: 30
  algorithm: "HS256"
  password_min_length: 10 