apiVersion: v1
kind: Secret
metadata:
  name: webagent-secrets
  namespace: webagent
  labels:
    app: webagent
    component: backend
type: Opaque
stringData:
  # IMPORTANT: Replace these placeholder values with actual keys
  # This file should never be committed to version control with real values
  # Use Kubernetes secret management or a tool like Sealed Secrets
  
  # API Keys
  openai-api-key: "replace-with-actual-openai-api-key"
  together-api-key: "replace-with-actual-together-api-key"
  tavily-api-key: "replace-with-actual-tavily-api-key"
  langsmith-api-key: "replace-with-actual-langsmith-api-key"
  
  # Security
  security-secret-key: "replace-with-secure-random-key-at-least-32-characters-long"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-password
  namespace: webagent
  labels:
    app: webagent
    component: redis
type: Opaque
stringData:
  # IMPORTANT: Replace with actual Redis password
  password: "replace-with-actual-redis-password" 